import type { Metadata } from "next";
import { inter, merriweather } from "@/ui/fonts";
import "@/ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${merriweather.variable} ${inter.variable} antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
